//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/FrontEndInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @FrontEndInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @FrontEndInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""FrontEndInput"",
    ""maps"": [
        {
            ""name"": ""FrontEnd"",
            ""id"": ""c9b9115a-f2f4-481b-8cb4-778d172c1ee1"",
            ""actions"": [
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Button"",
                    ""id"": ""f1cc52e0-b3ce-4a31-8623-51f6b11743cd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateController"",
                    ""type"": ""Value"",
                    ""id"": ""a19deb59-9de8-4e94-a801-7d04ad244e22"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""699b37a7-6f43-4031-8743-31676329b534"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0b83fb4-d4a9-483e-9ead-1de7b8b17c18"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateController"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // FrontEnd
        m_FrontEnd = asset.FindActionMap("FrontEnd", throwIfNotFound: true);
        m_FrontEnd_Rotate = m_FrontEnd.FindAction("Rotate", throwIfNotFound: true);
        m_FrontEnd_RotateController = m_FrontEnd.FindAction("RotateController", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // FrontEnd
    private readonly InputActionMap m_FrontEnd;
    private IFrontEndActions m_FrontEndActionsCallbackInterface;
    private readonly InputAction m_FrontEnd_Rotate;
    private readonly InputAction m_FrontEnd_RotateController;
    public struct FrontEndActions
    {
        private @FrontEndInput m_Wrapper;
        public FrontEndActions(@FrontEndInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Rotate => m_Wrapper.m_FrontEnd_Rotate;
        public InputAction @RotateController => m_Wrapper.m_FrontEnd_RotateController;
        public InputActionMap Get() { return m_Wrapper.m_FrontEnd; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FrontEndActions set) { return set.Get(); }
        public void SetCallbacks(IFrontEndActions instance)
        {
            if (m_Wrapper.m_FrontEndActionsCallbackInterface != null)
            {
                @Rotate.started -= m_Wrapper.m_FrontEndActionsCallbackInterface.OnRotate;
                @Rotate.performed -= m_Wrapper.m_FrontEndActionsCallbackInterface.OnRotate;
                @Rotate.canceled -= m_Wrapper.m_FrontEndActionsCallbackInterface.OnRotate;
                @RotateController.started -= m_Wrapper.m_FrontEndActionsCallbackInterface.OnRotateController;
                @RotateController.performed -= m_Wrapper.m_FrontEndActionsCallbackInterface.OnRotateController;
                @RotateController.canceled -= m_Wrapper.m_FrontEndActionsCallbackInterface.OnRotateController;
            }
            m_Wrapper.m_FrontEndActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Rotate.started += instance.OnRotate;
                @Rotate.performed += instance.OnRotate;
                @Rotate.canceled += instance.OnRotate;
                @RotateController.started += instance.OnRotateController;
                @RotateController.performed += instance.OnRotateController;
                @RotateController.canceled += instance.OnRotateController;
            }
        }
    }
    public FrontEndActions @FrontEnd => new FrontEndActions(this);
    public interface IFrontEndActions
    {
        void OnRotate(InputAction.CallbackContext context);
        void OnRotateController(InputAction.CallbackContext context);
    }
}
